## Importing the Libraries

In [0]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

##Importing Dataset

In [0]:
df=pd.read_csv("Holiday_Package.csv")
X=dataset.iloc[:,2:8].values
Y=dataset.iloc[:,1].values

In [0]:
print(X)
X.shape

[[48412 30 8 1 1 'no']
 [37207 45 8 0 1 'no']
 [58022 46 9 0 0 'no']
 ...
 [25178 24 6 2 0 'yes']
 [55958 41 10 0 1 'yes']
 [74659 51 10 0 0 'yes']]


(872, 6)

In [0]:
print(Y)

##Taking Care of Missing Values

###Looking for missing values

##"There are no missing values"

##Encoding Categorical Data

###Encoding Independent Variable

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[-1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)
X.shape

[[1.0 0.0 48412 ... 8 1 1]
 [1.0 0.0 37207 ... 8 0 1]
 [1.0 0.0 58022 ... 9 0 0]
 ...
 [0.0 1.0 25178 ... 6 2 0]
 [0.0 1.0 55958 ... 10 0 1]
 [0.0 1.0 74659 ... 10 0 0]]


(872, 7)

##Coding Dependent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [0]:
print(Y)

## Splitting The Data 

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [0]:
print(X_train)

[[1.0 0.0 45523 ... 11 0 0]
 [1.0 0.0 46220 ... 13 0 3]
 [1.0 0.0 38145 ... 13 0 0]
 ...
 [0.0 1.0 68467 ... 16 0 0]
 [1.0 0.0 45436 ... 11 0 0]
 [0.0 1.0 31241 ... 5 0 0]]


In [0]:
X_train.shape

(697, 7)

In [0]:
print(X_test)

[[1.0 0.0 44153 ... 4 0 0]
 [0.0 1.0 36839 ... 7 1 1]
 [1.0 0.0 68528 ... 8 0 1]
 ...
 [1.0 0.0 57010 ... 11 0 2]
 [1.0 0.0 29139 ... 7 0 2]
 [1.0 0.0 38927 ... 11 0 2]]


In [0]:
X_test.shape

(175, 7)

In [0]:
print(Y_train)

In [0]:
print(Y_test)

##Feature Scaling 

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 2:] = sc.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc.transform(X_test[:, 2:])

In [0]:
print(X_train)

[[1.0 0.0 -0.09989392280971206 ... 0.5380746544819581 -0.5202132880423415
  -0.9176362755585535]
 [1.0 0.0 -0.06919176436460187 ... 1.1977721640227232 -0.5202132880423415
  1.9082509883485679]
 [1.0 0.0 -0.4248875024481957 ... 1.1977721640227232 -0.5202132880423415
  -0.9176362755585535]
 ...
 [0.0 1.0 0.9107665124336287 ... 2.1873184283338705 -0.5202132880423415
  -0.9176362755585535]
 [1.0 0.0 -0.10372618648937432 ... 0.5380746544819581 -0.5202132880423415
  -0.9176362755585535]
 [0.0 1.0 -0.7290018523836919 ... -1.441017874140337 -0.5202132880423415
  -0.9176362755585535]]


In [0]:
X_train.shape

(697, 7)

In [0]:
print(X_test)

[[1.0 0.0 -0.16024106351243944 ... -1.7708666289107193
  -0.5202132880423415 -0.9176362755585535]
 [0.0 1.0 -0.48241550665094163 ... -0.7813203645995719 1.0984860948394086
  0.024326145743820318]
 [1.0 0.0 0.9134535019101735 ... -0.4514716098291894 -0.5202132880423415
  0.024326145743820318]
 ...
 [1.0 0.0 0.4060970299291415 ... 0.5380746544819581 -0.5202132880423415
  0.9662885670461941]
 [1.0 0.0 -0.8215928668049568 ... -0.7813203645995719 -0.5202132880423415
  0.9662885670461941]
 [1.0 0.0 -0.3904411783390476 ... 0.5380746544819581 -0.5202132880423415
  0.9662885670461941]]
